sudo: required
language: python
dist: precise
matrix:
  include:
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==0.7.10
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==0.8.7
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==0.9.10
    - python: 2.7
      env: CDH=cdh5 CDH_VERSION=5.10.1 PRESTO=0.147 SQLALCHEMY=sqlalchemy==1.0.19
install:
  - ./scripts/travis-install.sh
  - pip install codecov
# sleep so Presto has time to start up. Otherwise we might get 'No nodes available to run query'
script: sleep 10 && PYTHONHASHSEED=random pytest -v
after_success: codecov
